/*
 * dma.c
 *
 *  Created on: 26-Oct-2016
 *      Author: Shreyas
 */
/*
#include "dma.h"
#include "MKL25Z4.h"
#include "mcg.h"
#include "timer.h"


//volatile uint32_t count = 0;
//uint32_t a = 0;
//uint32_t b =0;
//uint32_t x = 0;
//uint32_t y =0;

void stop_timer();
void init_DMA_1Trans(void)

{

	unsigned char g8bSource[500]= "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA";
	unsigned char g8Destiny[500];

			SIM_SCGC6 |= SIM_SCGC6_DMAMUX_MASK;
			SIM_SCGC7 |= SIM_SCGC7_DMA_MASK;

			DMAMUX0_CHCFG0 = 0x00;
			DMA0->DMA[0].DSR_BCR= DMA_DSR_BCR_DONE_MASK;
			DMA_DSR_BCR0 |= 0x1F4u;
			DMA_SAR0 = (uint32_t)g8bSource;
			DMA_DAR0 = (uint32_t)g8Destiny;
			DMA_DCR0 |= DMA_DCR_EINT_MASK;
			DMA_DCR0 |= DMA_DCR_AA_MASK;
			DMA_DCR0 |= DMA_DCR_SSIZE(1)|DMA_DCR_DSIZE(1);

			DMA_DCR0 |= DMA_DCR_SINC_MASK;
			DMA_DCR0 |= DMA_DCR_DINC_MASK;

			DMAMUX0_CHCFG0 |= DMAMUX_CHCFG_ENBL_MASK;
			__enable_irq();
			NVIC_EnableIRQ(DMA0_IRQn);

			profiler_start();
			DMA_DCR0 |= DMA_DCR_START_MASK;
			//DMA_DSR_BCR0 |= 0x1000000u;

			//while(!(DMA_DSR_BCR0 & DMA_DSR_BCR_DONE_MASK));
			//profiler_stop();
			//x =TPM0_CNT;
			//y=x;

}

void DMA0_IRQHandler()
{
	DMA_DSR_BCR0 |= 0x1000000u;
	//if(DMA_DSR_BCR_DONE_MASK)
	profiler_stop();

	//a = count*480 + TPM0_CNT;
	//b=a;
}

*/
