/*
 * dma.c
 *
 *  Created on: 26-Oct-2016
 *      Author: Shreyas
 */

#include "dma.h"
#include "math.h"
#include "MKL25Z4.h"
#include "memory.h"
#include "mcg.h"
#include "timer.h"
#include "uart.h"
#define LENGTH 500


uint8_t  g8bSource[LENGTH]= "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA";
uint8_t  g8Destiny[LENGTH];
uint8_t *s;
uint8_t *d;
s= g8bSource;
d= g8bDestiny;

void init_DMA_1Trans(uint8_t *arr1,uint8_t *arr2,uint32_t length)   // DMA initialization function

{

			SIM_SCGC6 |= SIM_SCGC6_DMAMUX_MASK;
			SIM_SCGC7 |= SIM_SCGC7_DMA_MASK;

			DMAMUX0_CHCFG0 = 0x00;
			DMA0->DMA[0].DSR_BCR= DMA_DSR_BCR_DONE_MASK;
			DMA_DSR_BCR0 |= length;
			DMA_SAR0 = (uint32_t)arr1;
			DMA_DAR0 = (uint32_t)arr2;
			DMA_DCR0 |= DMA_DCR_EINT_MASK;
			DMA_DCR0 |= DMA_DCR_AA_MASK;
			DMA_DCR0 |= DMA_DCR_SSIZE(1)|DMA_DCR_DSIZE(1);

			DMA_DCR0 |= DMA_DCR_SINC_MASK;
			DMA_DCR0 |= DMA_DCR_DINC_MASK;

			DMAMUX0_CHCFG0 |= DMAMUX_CHCFG_ENBL_MASK;
			__enable_irq();
			//NVIC_EnableIRQ(DMA0_IRQn);

			profiler_start();
			DMA_DCR0 |= DMA_DCR_START_MASK;
			//DMA_DSR_BCR0 |= 0x1000000u;

}


int main()
{

	__disable_irq();
	UART0_init();
	init_DMA_1Trans(s,d,LENGTH);

	return 0;

}
